repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
        args: [ --allow-multiple-documents ]
      - id: check-xml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-merge-conflict
  - repo: https://github.com/digitalpulp/pre-commit-php.git
    rev: 1.4.0
    hooks:
      - id: php-lint
      - id: php-stan
        files: \.(php)$
#      - id: php-cs
#        files: \.(php)$
#        args: [--standard=PSR12 -p --exclude=PSR12.Files.FileHeader]
      - id: php-cbf
        files: \.(php)$
        args: [--standard=PSR12 -p --exclude=PSR12.Files.FileHeader]
